### DISCUSSION TITLE
comment the file content to the PR

### DISCUSSION THREAD

**Discussion by raghu-prasad-ttec** [actions/github-script#341] [Q&A]
The comment is showing as "$(cat sample.out)" instead of the actual file content. Below is the code for reference. Can someone what changes required to the "body: " in below code to get the required comment.

`      - name: set file as an output variable
        id: filestepid
        run: |
          echo 'FILE1_OUTPUT<<EOF' >> $GITHUB_OUTPUT
          echo '$(cat sample.out)' >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
  
      - name: Comment on PR
        uses: actions/github-script@v6.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.filestepid.outputs.FILE1_OUTPUT }}'
            })`

**Comment by joshmgross** [comment]
👋 In Bash, single quotes will cause the value to be taken literally rather than evaluating that command in the `$( )` block.

https://www.gnu.org/software/bash/manual/html_node/Single-Quotes.html

Try using `"` instead:

```bash
echo "$(cat sample.out)" >> $GITHUB_OUTPUT
```

Alternatively, you could redirect the output of `cat` directly:

```bash
cat sample.out >> $GITHUB_OUTPUT
```

**Comment by Sonichigo** [comment]
@joshmgross I'm doing something similar
```
  - id: keploytestreport
    name: Run Script
    run:  |
      ${GITHUB_ACTION_PATH}/install.sh > ${GITHUB_WORKSPACE}/${WORKDIR}/report.txt
      grep "TESTRUN SUMMARY. For testrun with id: " ${GITHUB_WORKSPACE}/${WORKDIR}/report.txt > ${GITHUB_WORKSPACE}/${WORKDIR}/final.txt
      grep "Total tests: " ${GITHUB_WORKSPACE}/${WORKDIR}/report.txt >> ${GITHUB_WORKSPACE}/${WORKDIR}/final.txt
      grep "Total test passed: " ${GITHUB_WORKSPACE}/${WORKDIR}/report.txt >> ${GITHUB_WORKSPACE}/${WORKDIR}/final.txt
      grep "Total test failed: " ${GITHUB_WORKSPACE}/${WORKDIR}/report.txt >> ${GITHUB_WORKSPACE}/${WORKDIR}/final.txt
      echo 'KEPLOY_REPORT<<EOF' > $GITHUB_OUTPUT
      cat ${GITHUB_WORKSPACE}/${WORKDIR}/final.txt >> $GITHUB_OUTPUT
      echo 'EOF' >> $GITHUB_OUTPUT
    shell: bash
    env:
      WORKDIR: ${{ inputs.working-directory }}
      DELAY: ${{ inputs.delay }}
      COMMAND : ${{ inputs.command }}
      KEPLOY_PATH: ${{inputs.keploy-path}}
  - name: Comment on PR
    uses: actions/github-script@v6
    with:
      github-token: ${{ github.token }}
      script: |
        github.rest.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: '${{ steps.keploytestreport.outputs.KEPLOY_REPORT }}'
        })`
```

But i'm getting "Error: Unhandled error: SyntaxError: Invalid or unexpected token"

**Reply by joshmgross** [reply]
@Sonichigo if `steps.keploytestreport.outputs.KEPLOY_REPORT` has multiple lines or quotes, it could be invalid JavaScript, example:


```js
        github.rest.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: ' some output, 
with a newline'
        })
```

The expression is evaluated before the JavaScript script, and it's not going to be escaped or anything to become valid JS.
The workaround is to pass the output as an `env` value:

```yaml
  - name: Comment on PR
    uses: actions/github-script@v6
    env:
      KEPLOY_REPORT: steps.keploytestreport.outputs.KEPLOY_REPORT
    with:
      github-token: ${{ github.token }}
      script: |
        github.rest.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: process.env.KEPLOY_REPORT
        })`
```

**Reply by Sonichigo** [reply]
when using with env I get new error:- ``SyntaxError: Unexpected end of input``

```yml
name: Comment on PR
    uses: actions/github-script@v6
    env:
      KEPLOY_REPORT: steps.keploytestreport.outputs.KEPLOY_REPORT
    with:
      github-token: ${{ github.token }}
      script: |
        github.rest.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: process.env.KEPLOY_REPORT
        })`
```

**Reply by joshmgross** [reply]
@Sonichigo looks like there's an extra ` in that example at the end, try this:

```yaml
  - name: Comment on PR
    uses: actions/github-script@v6
    env:
      KEPLOY_REPORT: ${{ steps.keploytestreport.outputs.KEPLOY_REPORT }}
    with:
      github-token: ${{ github.token }}
      script: |
        github.rest.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: process.env.KEPLOY_REPORT
        })
```
