### DISCUSSION TITLE
How to build file path for a JS import from within a reusable workflow

### DISCUSSION THREAD

**Discussion by jasongitmail** [actions/github-script#417] [Q&A]
I have 2 workflows:
1. an initiating workflow in my application repo ("repo A") 
2. a [reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow) within a different repo  

This works well, except when using `github-script` within the reusable workflow, because I'm unable to build a correct file path:

```yaml
       - name: Call my JS file
         uses: actions/github-script@v6
         with:
           script: |
             const fs = require('fs');
             const { foo } = await import(`${ process.cwd() }/lib/foo.js`)
```

I've tried:
- `github.action_path` but this is the path for repo A.  ` /home/runner/work/myproj/myproj` (like suggested here for "[composite actions](https://github.com/actions/github-script/issues/322)", which are different)
- `github.workspace` same path, as above, for repo A. ` /home/runner/work/myproj/myproj`
- `github.path` gives `/home/runner/work/_temp/_runner_file_commands/add_path_1d4d143f-7e45-4181-a863-88f16a7740fc"`, which won't help me build the file import path. 
- `${ process.cwd() }/lib/foo.js`

I have no luck getting the import to work. 

Any suggestions?
