### DISCUSSION TITLE
How to reference a separate script file which processes and returns output?

### DISCUSSION THREAD

**Discussion by rdhar** [actions/github-script#433] [Q&A] [answered]
Hi, I would like to strip out snippets of JS code into separate files outside of YAML for ease of legibility. However, I'm struggling to understand how best to achieve something this. 

##### Before/Current

```yml
script: |
    const { data: list_comments } = await github.rest.issues.listComments({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    per_page: 100,
    repo: context.repo.repo,
  });
  const get_comment = list_comments
    .sort((a, b) => b.id - a.id)
    .find((comment) => /^keyword/.test(comment.body));
  return {
    body: get_comment.body,
    id: get_comment.id,
  };
```

##### After/Proposed

```yml
script: |
  require(process.env.GITHUB_ACTION_PATH + '/comment.js');
```

```js
// File: comment.js
const { data: list_comments } = await github.rest.issues.listComments({
  issue_number: context.issue.number,
  owner: context.repo.owner,
  per_page: 100,
  repo: context.repo.repo,
});
const get_comment = list_comments
  .sort((a, b) => b.id - a.id)
  .find((comment) => /^keyword/.test(comment.body));
return {
  body: get_comment.body,
  id: get_comment.id,
};
```

With this, I get: "SyntaxError: await is only valid in async functions and the top level bodies of modules."
If I drop the `await`, then I get: "ReferenceError: github is not defined."

I'm sure I'm missing something obvious with `module.exports = ({ github, context }) => { ... }`, but I'm not sure how best to address this particular script which: makes an API call, processes the response, and returns the output in that specific order.

Really appreciate any thoughts/inputs, thanks for your time.
