### DISCUSSION TITLE
How to use multiline variable in a script

### DISCUSSION THREAD

**Discussion by baxelrod-bdai** [actions/github-script#458] [Q&A]
I am having trouble using a multiline variable in the `script` part of action `actions/github-script@v6`.

I found out how to convert it to a one line string, and this works fine in the `run` part of a second step.  For example, this works:

```
    steps:
    - name: Step1
      id: stepone
      run: |
        long_test_string="line one
          line two
          line three"

        echo "Long test string:"
        echo $long_test_string

        LONG2=${long_test_string}
        LONG2="${LONG2//'%'/'%25'}"
        LONG2="${LONG2//$'\n'/'%0A'}"
        LONG2="${LONG2//$'\r'/'%0D'}"
        echo "long2=$LONG2" >> "$GITHUB_OUTPUT"
       
    - name: Step2
      run: |
        echo "${{ steps.stepone.outputs.long2 }}"
```

However, when I try to display this in a PR comment, I get an error.

```
    - name: Step3
      uses: actions/github-script@v6
      with:
        script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ steps.stepone.outputs.long2 }}"
            })
```

**Comment by joshmgross** [comment]
I'd recommend passing inputs through an environment variable into your script rather than inlining the expression.

https://github.com/actions/github-script#use-env-as-input

For example:
```yaml
    - name: Step3
      uses: actions/github-script@v6
      env:
        LONG_OUTPUT: ${{ steps.stepone.outputs.long2 }}
      with:
        script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.LONG_OUTPUT
            })
```
