### DISCUSSION TITLE
Catching 404 response when calling github.rest.repos.getReleaseByTag()

### DISCUSSION THREAD

**Discussion by thomasleplus** [actions/github-script#468] [Q&A] [answered]
Hi,

I apologize in advance if this is a beginner's question but I am not a node expert so I am struggling a bit to do something that is probably pretty simple. I currently have the following step in my workflow:

```Yaml
- name: Check if release already exists
  id: check-release
  uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
  script: |
    const { VERSION } = process.env
    github.rest.repos.getReleaseByTag({
      owner: context.repo.owner,
      repo: context.repo.repo,
      tag: `v${VERSION}`,
    })
```

This step succeeds when the tag exists and fails (`Unhandled error: HttpError: Not Found`) when the tag doesn't. Instead I would like the step to succeed for both 200 and 404 responses (but not 400, 401 etc) and to be able to tell the difference between 200 and 404 in the following steps. For example it would return an empty result when the response is 404, or it could return the response status itself (since I don't use the body of the getReleaseByTag() response at the moment). I found discussions on how to do this by invoking the underlying REST API (https://github.com/actions/github-script/discussions/386) but I'd rather find a way to do it using the more convenient getReleaseByTag() method. Any suggestion on how to do this?

Regards,

Thomas
