### DISCUSSION TITLE
What permissions are required for github.rest.teams.listMembersInOrg?

### DISCUSSION THREAD

**Discussion by johnbatclari** [actions/github-script#481] [Q&A]
I'm struggling to find what permissions are required to be able to make `github.rest.teams.listMembersInOrg` calls. I'm currently getting 404's when a workflow is triggered by a `pull_request`, though I can successfully execute the workflow if I run it using `netkos/act` locally. I've searched docs without success. Any help would be much appreciated!

Currently configured permissions:
```yaml
permissions:
  contents: read
  pull-requests: write
```

And the call in question:
```yaml
      - name: Check for approvals
        id: needs-approvals
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: approvalTeamMembers } = await github.rest.teams.listMembersInOrg({
                org: 'myorg',
                team_slug: 'myteam'
            });
            console.debug(`Team members: ${approvalTeamMembers.map(member => member.login).join(', ')}`);
```
