### ISSUE TITLE
Please consider retries for the Octokit client

### ISSUE THREAD

**Issue by awendt** [actions/github-script#104]
**Is your feature request related to a problem? Please describe.**

I just ran into a problem where a call to the Github API unexpectedly returned a 404 error. This failed our workflow. The error was intermittent and wasn't reproducible when I re-ran the job.

**Describe the solution you'd like**

I'd like any API calls made by the `github` client to be retried, preferably using the [retry plugin](https://github.com/octokit/plugin-retry.js)

**Describe alternatives you've considered**

I've considered adding the retry logic to our workflow but this defeats the purpose of having a pre-authenticated API client.

**Comment by joshmgross** [comment]
Since not all consumers may want this behavior, we could support it behind an optional input

```yaml
  enable-retries:
    description: Whether to use the retry plugin to retry GitHub requests
    default: false
```
