### ISSUE TITLE
Provide a more clear await example in the README

### ISSUE THREAD

**Issue by JPrendy** [actions/github-script#115]
**Is your feature request related to a problem? Please describe.**
Apologies, If I am doing this incorrectly. I would like to use your `https://github.com/actions/github-script/blob/main/.github/workflows/pull-request-test.yml` example in a separate file instead of an inline script.

**Describe the solution you'd like**
So, I originally looked at your solution in `https://github.com/actions/github-script/blob/main/.github/workflows/pull-request-test.yml`, but noticed it was all done in an inline script, I think it would be helpful if you provided a more extensive example in the README as it took me a few trys to get it working in a separate file.

**Describe alternatives you've considered**

**Additional context**
So, if you could provide something like the following in the README, I think it would be helpful for other people as the example in `https://github.com/actions/github-script/blob/main/.github/workflows/pull-request-test.yml` is quite good and uses await.

```
on: push


jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/path/to/script.js`)
            await script({github, context})
```

and then in that js file have

```
module.exports = async ({ github, context }) => {
  // Get the existing comments.
  const { data: comments } = await github.issues.listComments({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: context.payload.number,
  })
  
  // Find any comment already made by the bot.
  const botComment = await comments.find(comment => comment.user.id === 41898282)
  const commentBody = "Hello from actions/github-script! (${{ github.sha }})"

  if (botComment) {
    return await github.issues.updateComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      comment_id: botComment.id,
      body: commentBody
    })
  } else {
    return await github.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: context.payload.number,
      body: commentBody
    })
  }
}
```

**Comment by joshmgross** [comment]
Thanks @JPrendy, feel free to open a PR to add or improve any of the examples.

**Comment by leandredasilva** [comment]
Hi

It took me a few tries to have github-script run a separate file with async/await, so as suggested, I opened a PR to add an example.

Please let me know if I'm missing something.

**Comment by JPrendy** [comment]
Thanks for creating a pr @leandredasilva, I have been too busy unfortunately to create the pr myself.

**Comment by joshmgross** [comment]
Merged #131, thanks all!

**Comment by jasondamour** [comment]
The example did not work out of the box for me. I had to install the async module myself:
```
    # Without this step, it fails with vague MODULE_NOT_FOUND
    - run: npm install --no-save async


    - uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          const commentOnPR = require('${{ github.workspace }}/scripts/terraform-pr-comment.js')
          await commentOnPR({github, context, steps})
```
