### ISSUE TITLE
TypeError: github.repos.createOrUpdateEnvironment is not a function - Octokit.js Support up-to-date?

### ISSUE THREAD

**Issue by James-LeHa** [actions/github-script#133]
**Is your feature request related to a problem? Please describe.**
Trying to use github-script for environments but getting this error message:
`TypeError: github.repos.createOrUpdateEnvironment is not a function`

**Describe the solution you'd like**
Would you all be able to update the version of Octokit.js that supports [Repo Environments](https://octokit.github.io/rest.js/v18#repos-create-or-update-environment)

**Describe alternatives you've considered**
Using actions to post the HTTP response for environment creation

**Additional context**
![image](https://user-images.githubusercontent.com/62304682/114341479-e13f8b80-9b27-11eb-8693-a0864e88b8f1.png)

**Comment by Simran-B** [comment]
Just ran into a similar issue:
`Error: Unhandled error: TypeError: github.actions.getEnvironmentPublicKey is not a function`

Several functions were added to Octokit here: https://github.com/octokit/octokit.js/pull/2025
I suppose `github-script` needs to bump its dependencies?

**Comment by Simran-B** [comment]
I got it to work with a modified version of this action (bumped deps):

```yaml
name: Secrets

on:
  push:
    branches:
      - main

jobs:
  set-secret:
    name: Create or update environment secret
    runs-on: ubuntu-latest
    steps:
      - name: Install tweetsodium
        run: |
          npm install tweetsodium
      - uses: Simran-B/github-script@main # has updated dependencies (for testing only!)
        id: update-secret
        with:
          github-token: ${{ secrets.PAT }} # Personal access token required
          # (also for retrieving the env public key, despite what the documentation claims)
          script: |
            const sodium = require('tweetsodium')

            const envName = "prod"
            const secretName = "MY_SECRET"
            const value = "New secret value"

            const pkey = await github.rest.actions.getEnvironmentPublicKey({
              repository_id: context.payload.repository.id,
              environment_name: envName,
            })

            const messageBytes = Buffer.from(value)
            const keyBytes = Buffer.from(pkey.data.key, "base64")
            const encryptedBytes = sodium.seal(messageBytes, keyBytes)
            const encrypted = Buffer.from(encryptedBytes).toString("base64")

            const result = await github.rest.actions.createOrUpdateEnvironmentSecret({
              repository_id: context.payload.repository.id,
              environment_name: envName,
              secret_name: secretName,
              encrypted_value: encrypted,
              key_id: pkey.data.key_id,
            })
            console.log(result.status)
```
