### ISSUE TITLE
No `result` from `github.pulls.get`?

### ISSUE THREAD

**Issue by callum-tait-pbx** [actions/github-script#142]
I'm trying to post to the deployment API when a certain comment is added to a PR. The deployment API requires the branch and so I need to get the branch from the pull request as this isn't provided in the github context from this trigger type annoyingly.

I don't seem to get any results back though from trying to query the pull API. I'm sure I'm doing something wrong but for the life of me I can't figure out what:

```yaml
on:
  issue_comment:
    types:
      - created

name: On PR Comment Do Something

jobs:
  comment:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: pull_request_payload
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
      - run: echo "${{ steps.pull_request_payload.outputs.result }}"
```

If I try to echo out the result I get nothing

I'm really struggling to understand how to use the context object, in addition I don't really get where `context.repo.owner` and `context.repo.repo` are set, are they just added to the context by the action whenever it is invoked?

EDIT

I've also tried with `pull_number: "${{ github.event.issue.number }}"` which gives the right PR number but I still don't get anything from my echo statement in the next step

**Comment by chinchang** [comment]
same here. I get the following error:
```
SyntaxError: Unexpected identifier
```

**Comment by joshmgross** [comment]
👋  Hey @callum-tait-pbx,

You'll need to explicitly return the value for it to be set as an output - https://github.com/actions/github-script#reading-step-results

```diff

      - uses: actions/github-script@v4
        id: pull_request_payload
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
-            github.pulls.get({
+            return github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
      - run: echo "${{ steps.pull_request_payload.outputs.result }}"
```

>I'm really struggling to understand how to use the context object, in addition I don't really get where context.repo.owner and context.repo.repo are set, are they just added to the context by the action whenever it is invoked?

The `context` object comes from the `@actions/github` package, you can see how it's created in 
https://github.com/actions/toolkit/blob/main/packages/github/src/context.ts


It's only a specific set of the environment variables available, for the full set I'd recommend printing out the environment in your workflow for the event you're using.

```yaml
    - name: Output Run Env
      run: printenv
      shell: bash
  
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
```
