### ISSUE TITLE
Make an API call to a self-hosted/enterprise instance 

### ISSUE THREAD

**Issue by UbiquitousBear** [actions/github-script#150]
**Is your feature request related to a problem? Please describe.**
It looks like there's no way to configure the API host: https://github.com/actions/github-script/blob/main/action.yml

**Describe the solution you'd like**
Ability to configure the API host to make it compatible with GitHub Enterprise Server.

**Comment by joshmgross** [comment]
👋  Hey @UbiquitousBear, you should be able to be able to set the API URL using the `GITHUB_API_URL` environment variable - 

https://github.com/actions/toolkit/blob/11601c0d2dbb2d2cf287c77d03cc3e53866a4f56/packages/github/src/internal/utils.ts#L23-L25


Example:

```yaml
      - uses: actions/github-script@v4
        env:
          GITHUB_API_URL: 'https://example.com'
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
```
