### ISSUE TITLE
pull_request workflow for specific branch not triggering

### ISSUE THREAD

**Issue by basickarl** [actions/github-script#206]
```
    name: blabla bacon n eggs
    on:
        pull_request:
            branches:
                - basickarl/gh-actions-pr
    
    defaults:
        run:
            shell: bash
    
    jobs:
        somting:
            runs-on: ubuntu-latest
            steps:
                - run: echo "testy"

```
I have pushed my code on the branch stated to the origin repo in github. I have created a pull request. I updated some code on the branch and pushed, but the actions is not triggering? How does one trigger a github action workflow when updating a pull request?

The updates to the branch I am making is the workflow file itself.

Here is an example repo: https://github.com/basickarl/github-actions/actions/workflows/test.yaml

For some reason only `on: [pull_request]` seems to work.

It states here that you should be able to use branches: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-multiple-events-with-activity-types-or-configuration
