### ISSUE TITLE
console.assert(false) doesn't fail the step

### ISSUE THREAD

**Issue by alecmocatta** [actions/github-script#207]
**Describe the bug**

```yaml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v5
      with:
        script: |
          console.assert(false)
```
prints:
```text
Assertion failed
```

but execution continues and the step passes, rather than fails.
