### ISSUE TITLE
SyntaxError: Unexpected token ','

### ISSUE THREAD

**Issue by joshuajeschek** [actions/github-script#218]
I get `SyntaxError: Unexpected token ','`, when running my workflow. I am using github.rest.actions.createWorkflowDispatch. This is my workflow:
```yaml
name: update
on:
  push:
    branches:
      - main
jobs:
  dispatch-update:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch update
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              'weichware-10',
              'util',
              'workflows/update.yaml',
              'main',
              inputs: {
                message: ${{ github.event.head_commit.message }},
              },
            });
          debug: true
```

Also, I don't know if I did the inputs thingy correctly. Thanks for your help!

Please let me know if I should provide any additional information :)
