### ISSUE TITLE
Unexpected token 'var'

### ISSUE THREAD

**Issue by tjbaker** [actions/github-script#220]
I am trying to comment on a PR via a workflow and keep getting this exception:

```
SyntaxError: Unexpected token 'var'
    at new AsyncFunction (<anonymous>)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4942:56)
    at main (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4997:26)
    at Module.272 (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4981:1)
Error: Unhandled error: SyntaxError: Unexpected token 'var'
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:52:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

The code is really simple

```
      - name: Comment on PR
        uses: actions/github-script@v5
        if: failure()
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "foo"
            })
```

Github support asked me to log a bug report here as well.

**Comment by joshmgross** [comment]
👋  Hey @tjbaker

What event is this workflow triggering on?

It's possible that `context.issue.number` isn't valid.

If it's helpful, you can print out the full `context.issue`:

```yaml
      - name: Comment on PR
        uses: actions/github-script@v5
        if: failure()
        with:
          script: |
            console.log(JSON.stringify(context.issue))
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "foo"
            })
```

**Comment by tjbaker** [comment]
Ok, I think the actual problem is with using a multiline output from a previous step's stdout as the body in createComment.
Do you have a working example of that?

**Comment by cemo** [comment]
@tjbaker did you resolve your issue?

**Comment by joshmgross** [comment]
> Ok, I think the actual problem is with using a multiline output from a previous step's stdout as the body in createComment.

If you need to pass into multi-line outputs into the `script` block, you'll likely need to pass those values in as environment variables. Otherwise, newlines will be interpreted literally in the script and won't be valid JavaScript.

Example:

```yaml
- uses: actions/github-script@v5
  env: 
    MULTILINE_VALUE: ${{ steps.my_step.outputs.value }}
  with:
    script: |
        github.issues.createComment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: process.env.MULTILINE_VALUE
        })
```

**Comment by jsumners** [comment]
I am having this issue where the error message is:

```
SyntaxError: Invalid or unexpected token
    at new AsyncFunction (<anonymous>)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4797:16)
...
```

My step looks like:

```yaml
      - name: Post comment
        uses: actions/github-script@v6
        with:
          script: |
            const comment = '
              Data for `${{ steps.get_id.outputs.an_id }}`:

              ```json
              ${{ steps.get_data.outputs.result }}
              ```';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
```

Where `steps.get_data.outputs.result` is a large JSON object with formatting.
