### ISSUE TITLE
Bug can't create card from pull request with v5

### ISSUE THREAD

**Issue by sylhare** [actions/github-script#223]
**Describe the bug**
Hello @joshmgross , it seems I can't add PR to the project board using personal access token with admin:org, repo and workflow rights using actions/github-script@v5
(I tried to create a card from an [issue](https://github.com/UpstreamOrg/UpstreamRepo/issues/10) and it worked fine.)

**To Reproduce**
On `pull_request_target` I used with this yaml:
```yml
      - name: Add PR to project board
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.ADMIN_PAT }}
          script: |
            github.rest.projects.createCard({
            column_id: 17134543, # IN_PROGRESS column
            content_id: context.payload.pull_request.id,
            content_type: "PullRequest"
            });
```

And I get this error:

```bash
Run actions/github-script@v5
  with:
    github-token: ***
    script: github.rest.projects.createCard({
  column_id: 17134543, # IN_PROGRESS column
  content_id: context.payload.pull_request.id,
  content_type: "PullRequest"
  });
  
    debug: false
    user-agent: actions/github-script
    result-encoding: json
SyntaxError: Invalid or unexpected token
Error: Unhandled error: SyntaxError: Invalid or unexpected token
    at new AsyncFunction (<anonymous>)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4942:56)
    at main (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4997:26)
    at Module.272 (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4981:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:52:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```    

However this previous version `actions/github-script@626af12fe9a53dc2972b48385e7fe7dec79145c9`, then it is working:
```yml
      - name: Add PR to project board using old action
        uses: actions/github-script@626af12fe9a53dc2972b48385e7fe7dec79145c9
        with:
          github-token: ${{ secrets.ADMIN_PAT }}
          script: |
            try {
              await github.projects.createCard({
                column_id: 17134543,
                content_id: context.payload.pull_request.id,
                content_type: "PullRequest"
              });
            } catch (error) {
              console.log(error);
            };
```

There are no error and the card gets created. I used both in the same jobs so they had both access to the same secret, I used the `.rest` for projects because it's v5. But maybe the way to pass the token has changed, and I did not see clear documentation on how to pass it now.

**Expected behavior**
The `actions/github-script@v5` should be able to create the card on the project for the PR with the right access token.

**Screenshots**
<img width="830" alt="image" src="https://user-images.githubusercontent.com/20642750/145437151-1cf2af37-49c0-4020-8774-83930b5ab4b4.png">

**Additional context**
You can find the workflow run here: https://github.com/UpstreamOrg/UpstreamRepo/runs/4473194405?check_suite_focus=true

**Comment by joshmgross** [comment]
👋  @sylhare,

```yaml
      - name: Add PR to project board
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.ADMIN_PAT }}
          script: |
            github.rest.projects.createCard({
            column_id: 17134543, # IN_PROGRESS column
            content_id: context.payload.pull_request.id,
            content_type: "PullRequest"
            });
```
>SyntaxError: Invalid or unexpected token

Can you try removing that comment "# IN_PROGRESS column"? It might be getting evaluated in the `script` block by the action
