### ISSUE TITLE
Feature request: Deno as runtime ?

### ISSUE THREAD

**Issue by mykiwi** [actions/github-script#231]
Hi,

Does anyone already though about using [Deno](https://deno.land) as script runtime?
I would love to be able to code in typescript, or just avoid npm stuff before this step like:
```yml
      - run: npm ci
      # or one-off:
      - run: npm install execa
      - uses: actions/github-script@v5
        with:
          script: |
            const execa = require('execa')

            const { stdout } = await execa('echo', ['hello', 'world'])

            console.log(stdout)
```
to
```yml
      - uses: actions/github-script@v5
        with:
          script: |
            import { execa } from "https://esm.sh/execa@6";

            const { stdout } = await execa('echo', ['hello', 'world'])

            console.log(stdout)
```

What do you think?
