### ISSUE TITLE
Setting mediaType doesn't work

### ISSUE THREAD

**Issue by T3rm1** [actions/github-script#243]
What version of octokit is used in this action? I'm trying to get the contents of a file in a repository with:
```
github.rest.repos.getContent({
  owner,
  repo,
  path,
  mediaType: {
    format: "raw+json"
  }
});
```
but it doesn't work. I always get the default response as if mediaType isn't set. Maybe this is not yet supported in the octokit client used in this action?

I looked at the debug information of the request and the headers don't include an `Accept` header. I expect the `Accept` header to be set to `application/vnd.github.v3.raw+json`

**Comment by joshmgross** [comment]
> What version of octokit is used in this action?

If you're on the latest version of this action, we're using Octokit 3.5.1
https://github.com/actions/github-script/blob/main/package.json#L39

**Comment by T3rm1** [comment]
I see, thanks for the response. I figured out what I misunderstood. I thought that setting the media type to `raw+json` would be the same as doing the request with the header `Accept; application/vnd.github.v3.raw+json`. Apparently that is not the case. The only thing that changes is the data key in the returned json object.

Example: https://api.github.com/repos/actions/github-script/contents/README.md
If you open the link in the browser you get json object.
If you open the link in the browser and set the header `Accept; application/vnd.github.v3.raw` you only get the contents of the file.
If you use octokit to request the conent with
```
await octokit.request("GET /repos/{owner}/{repo}/contents/{path}", {
    owner: "actions",
    repo: "github-script",
    path: "README.md",
    mediaType: {
      format: "raw"
    }
})
```
you get a different json object. That's totally confusing and I haven't found anything about this in the octokit documentation.

**Comment by T3rm1** [comment]
Ok I have to reopen this. I did the above test directly with node and not in the context of the GitHub script action. I tested it with this action and it doesn't work, although the mediaType is set. I still get the base64 encoded data as a response.

I also noticed that the User-Agent is set to `actions/github-script`. Maybe this is the issue or maybe even more fields are changed by this action so that it won't pass on the mediaType.

**Comment by T3rm1** [comment]
@joshmgross 
I set up a reproducible test case here: https://github.com/T3rm1/github-script-bug/runs/5419408653?check_suite_focus=true#step:2:57

As you can see, the content is encoded as base64 although the mediaType format is set to raw. As I don't get this error when I run this with the latest octokit in node directly, I assume this must be a bug of this action.

Can you have a look, please?

**Comment by avonengel** [comment]
I ran into the same issue and was able to work around it like this:
```yml
      - name: install npm packages
        run: |
          npm install @octokit/rest @actions/github

      - uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const { getOctokitOptions } = require('@actions/github/lib/utils');

            const github2 = new Octokit(getOctokitOptions(process.env.GITHUB_TOKEN));
```

Of course this is suboptimal, but at least it behaves the same as when run directly via node locally, or from within custom JS actions.
