### ISSUE TITLE
core.error() does not fail the workflow

### ISSUE THREAD

**Issue by T3rm1** [actions/github-script#245]
According to https://github.com/actions/toolkit/tree/main/packages/core#annotations this code should fail the build: `core.error('Fatal error')`. It does not. The workflow succeeds.

```
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: Fail workflow
        uses: actions/github-script@v6.0.0
        with:
          script: core.error('Fatal error')
```

I can see the annotation on the actions page but not on the pull request page. Also I get a green checkmark indicating that the workflow was successfull.
