### ISSUE TITLE
POST request for creation `workflow_dispatch` event doesn't work from `github-script`

### ISSUE THREAD

**Issue by mckrava** [actions/github-script#246]
**Describe the bug**
I need run one workflow from another one. I'm trying to use for this github-script and github API. If I test this request from Postman, jsfiddle or `curl`, it works and runs required workflow.
These work:
- in jsFiddle
```javascript
import { request } from "https://cdn.skypack.dev/@octokit/request";
await request({
        headers: {
          accept: 'application/vnd.github.v3+json',
          authorization: `Token ***`,
        },
        method: 'POST',
        url: `https://api.github.com/repos/owner/repo/actions/workflows/42/dispatches`,
        data: {
          ref: 'develop',
        },
      });
```
- in workflow step:
```yaml
- name: Curl test
   shell: bash
   run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GH_TOKEN" \
          https://api.github.com/repos/owner/repo/actions/workflows/42/dispatches \
          -d '{"ref":"develop"}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
```

But these don't work:
```yaml
- uses: actions/github-script@v6
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          script: |
            const { GH_TOKEN } = process.env;

            await github.request({
                headers: {
                  accept: 'application/vnd.github.v3+json',
                  authorization: `Token ${GH_TOKEN}`,
                },
                method: 'POST',
                url: `https://api.github.com/repos/owner/repo/actions/workflows/42/dispatches`,
                data: {
                  ref: 'develop',
                },
            });
```
```yaml
- uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
                owner: 'owner',
                repo: 'repo',
                workflow_id: 42,
                ref: 'develop',
            });
```
If I move requests logic to separate JS file, result is the same - dispatch is not happening but requests return `204` what is OK for this action. 
```yaml
      - uses: actions/github-script@v6
        id: issue-comment-data
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          script: |
            const script = require('./scripts/ci/dispatch-workflow.js')
            await script({github, context, core})
```

I can post comment into issues and make any GET requests from `github-script` but this particular request doesn't work properly. 

**Expected behavior**
I should be able create `workflow_dispatch` event from `github-script`.

**Comment by joshmgross** [comment]
@mckrava I'm not sure if you're passing in your token correctly, can you try the `github-token` input?
https://github.com/actions/github-script/blob/main/action.yml#L11-L14

```yaml
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
                owner: 'owner',
                repo: 'repo',
                workflow_id: 42,
                ref: 'develop',
            });
```
