### ISSUE TITLE
Use secrets in the script

### ISSUE THREAD

**Issue by naquiroz** [actions/github-script#253]
**Is your feature request related to a problem? Please describe.**
I use the secrets inside the script.

**Describe the solution you'd like**
I would like to have the object `secrets` available, to use them in the script. For example, I would like to hash the secrets object.

**Describe alternatives you've considered**
Passing the secrets object as a string from the env. Although it might work, it is too much overhead.

**Comment by TWiStErRob** [comment]
(user here, not contributor)

Another alternative is to use `script: | ... ${{ secrets.MY_SECRET }} ...`, but I think that's hardly secure as it'll output the script contents before executing. Might obfuscate it though, do try if you haven't yet.

**Comment by joshmgross** [comment]
This isn't something we'll support as a built-in context - every script would have access to all of the secrets for a job.

If you want the full `secrets` object, I'd recommend passing it in as an environment variable:

```yaml
      - name: Access all the secrets 🔒
        uses: actions/github-script@v6
        env:
          SECRETS: ${{ toJSON(secrets) }}
        with:
          script: |
            console.log(process.env.SECRETS)
```
