### ISSUE TITLE
core.getInput (and maybe other things) doesn't work in another action

### ISSUE THREAD

**Issue by daleyjem** [actions/github-script#258]
Please let me know if I'm just doing things wrong, but when `actions/github-script` is used within another action, things like `core.getInput('some_input)` don't return anything.

I have a test here to demonstrate: https://github.com/daleyjem/test-github-script/pull/1

## Workflow File

```yml
name: Test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test input
        uses: ./.github/actions/test-input
```

## Action File

```yml
name: Test Input
description: Test input
inputs:
  my_input: 
    description: My input
    required: false
    default: 'foobar'

runs:
  using: 'composite'
  steps:
    - name: Log input val
      uses: actions/github-script@v6
      with:
        script: |
          console.log('my_input =', core.getInput('my_input'))
    - name: Log it the other way
      run: |
        echo ${{ inputs.my_input }}
      shell: bash
```

**Comment by eserte** [comment]
A possible workaround: interpolate your inputs into the script code:
```
          console.log('my_input =', "${{ inputs.my_input }}")
```
However this breaks if the input value contains certain characters, e.g. a double quote. And using this workaround it is even possible to inject additional javascript code into the action:
```
      - name: Test input
        uses: ./.github/actions/test-input
        with:
          my_input: 'foo"); console.log("ohoh'
```
So you have to be careful when using this workaround.
