### ISSUE TITLE
Error with Terraform Plan - Argument list too long

### ISSUE THREAD

**Issue by air3ijai** [actions/github-script#266]
**Describe the bug**
We got an error "Argument list too long" when trying to use this action with Terraform Plan

**To Reproduce**
1. Prepare code terraform code with a big Plan output
2. Use [github-script](https://github.com/actions/github-script) as described on [setup-terraform](https://github.com/hashicorp/setup-terraform)
3. Trigger workflow execution on PR

**Expected behavior**
We should see plan output in the issue comment and in case if it is too big it should be truncated.

**Screenshots**
<img width="1035" alt="Screenshot 2022-06-08 at 02 21 07" src="https://user-images.githubusercontent.com/88528265/172499180-7a174e66-eb74-4a6e-939a-a07a7f15cffd.png">

**Additional context**

**Comment by air3ijai** [comment]
https://github.com/actions/runner/issues/1733

**Comment by air3ijai** [comment]
https://github.com/robburger/terraform-pr-commenter/issues/6

**Comment by air3ijai** [comment]
https://github.community/t/maximum-length-for-the-comment-body-in-issues-and-pr/148867

**Comment by joshmgross** [comment]
@air3ijai could you try writing the Terraform plan to a file and reading the contents of that file in `github-script`?

**Comment by air3ijai** [comment]
@joshmgross, can you please provide an example how we can do this?

I just prepared a code which thrown the error.

#### Steps
1. Create test repository
2. Add AWS Auth secrets
    ```
    AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY
    ```
4. Create `main.tf` file
5. Create `.github/workflows/tf-plan.yaml`
6. Update the code in a different branch and create a PR
7. Update varible `TF_VAR_instance_count: 26` in `.github/workflows/tf-plan.yaml`


<details>
  <summary>main.tf</summary>

```
variable "instance_count" {
}

resource "aws_vpc" "my_vpc" {
  cidr_block = "172.16.0.0/16"

  tags = {
    Name = "tf-example"
  }
}

resource "aws_subnet" "my_subnet" {
  vpc_id            = aws_vpc.my_vpc.id
  cidr_block        = "172.16.10.0/24"
  availability_zone = "us-west-2a"

  tags = {
    Name = "tf-example"
  }
}

resource "aws_instance" "foo" {
  count         = var.instance_count
  ami           = "ami-005e54dee72cc1d00" # us-west-2
  instance_type = "t2.micro"

  credit_specification {
    cpu_credits = "unlimited"
  }
}
```
</details>

<details>
  <summary>tf-plan.yaml</summary>

```
name: Test Terraform Plan

on:

  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_VERSION: 1.2.2
  TF_VAR_instance_count: 25

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Terraform - Use Terraform ${{ env.TERRAFORM_VERSION }}
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform - Checkout
        uses: actions/checkout@v3

      - name: Terraform - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform - Format and style
        id: fmt
        run: terraform fmt -check -diff -recursive
        continue-on-error: true

      - name: Terraform - Init
        id: init
        run: terraform init

      - name: Terraform - Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform - Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform - Plan size
        id: plan-size
        run: ls -la

      - name: Terraform - Show Plan in PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ github.workspace }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
```
</details>

:white_check_mark:  25 instances `-rw-r--r-- 1 runner docker 402846 Jun 11 14:43 plan.out`

:x: 26 instances `-rw-r--r-- 1 runner docker 418537 Jun 11 14:44 plan.out`

**Comment by kylekurz** [comment]
+1 on this from me, just hit it this morning. I changed a global variable in our config that triggered > 100 resources to need an update. Will try the file idea, but wanted to bump that others are experiencing this too.

**Comment by kylekurz** [comment]
@air3ijai here's some help for you to move on until this can be tackled or better documented. This is my diff for the PR workflow, it was previously very close to the example from Hashi, so this should be something you can apply to your workflow too:

```
diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
index 5a3d0d5..260c671 100644
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -98,13 +98,23 @@ jobs:
         run: terraform plan -no-color
         continue-on-error: true
 
+      - name: Echo plan output to a file
+        run: |
+          echo "${{ steps.plan.outputs.stdout }}" > plan.out
+
+      - name: Install fs module
+        run: npm install fs
+
       - uses: actions/github-script@v6
         if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
+            const { readFile } = require("fs/promises")
+            const data = await readFile('plan.out')
+
+            const plan = "terraform\n" + data.length > 65000 ? `${data.substring(0, 65000)}...` : data
+
             // 1. Retrieve existing bot comments for the PR
             const { data: comments } = await github.rest.issues.listComments({
               owner: context.repo.owner,
@@ -121,7 +131,7 @@ jobs:
             <details><summary>Show Plan</summary>
 
             \`\`\`\n
-            ${process.env.PLAN}
+            ${plan}
             \`\`\`
 
             </details>
```

**Comment by air3ijai** [comment]
@kylekurz, thank you for your solution, I have adopted and tested it.
<details><summary>tf-plan.yaml</summary>

```
name: Test Terraform Plan

on:

  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_VERSION: 1.2.2
  TF_VAR_instance_count: 1

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Terraform - Use Terraform ${{ env.TERRAFORM_VERSION }}
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Terraform - Checkout
        uses: actions/checkout@v3

      - name: Terraform - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform - Format and style
        id: fmt
        run: terraform fmt -check -diff -recursive
        continue-on-error: true

      - name: Terraform - Init
        id: init
        run: terraform init

      - name: Terraform - Validate
        id: validate
        run: |
          terraform validate
          echo "::set-output name=stdout::$(terraform validate -no-color)"

      - name: Terraform - Plan
        id: plan
        run: terraform plan -no-color -out=plan.out

      - name: Terraform - Show Plan in PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const plan_file = fs.readFileSync('plan.out','utf8')
            const plan = plan_file.length > 65000 ? plan_file.toString().substring(0, 65000) + " ...\r\n\nOutput is too long and was truncated. You can read full plan in Actions." : plan_file
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${plan}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ github.workspace }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
```
</details>

And some notes
1. Error `Argument list too long` is related to the variable assignment
   ```yaml
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
   ```
   And same error we got if we try to assign stdout to the javascript variable
   ```js
   const plan_env = `${{ steps.plan.outputs.stdout }}`
   ```
    In such a case a remained solution is to use a file

2. By default, in [Terraform actions](https://github.com/hashicorp/setup-terraform) `terraform_wrapper: true` and in case of the short plan you will see some additional output - [How can I remove all the extraneous output from redirected output in GitHub Actions?](https://stackoverflow.com/questions/66496105/how-can-i-remove-all-the-extraneous-output-from-redirected-output-in-github-acti). But when it is disabled you can't directly access `Validation Output` and it will be empty. This is why we set it manually.

**Comment by air3ijai** [comment]
@kylekurz, thank you for your solution, I have adopted and tested it.


<details><summary>tf-plan.yaml</summary>

```yaml
name: Test Terraform Plan

on:

  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_VERSION: 1.2.2
  TF_VAR_instance_count: 30

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Terraform - Use Terraform ${{ env.TERRAFORM_VERSION }}
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Terraform - Checkout
        uses: actions/checkout@v3

      - name: Terraform - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform - Format and style
        id: fmt
        run: terraform fmt -check -diff -recursive
        continue-on-error: true

      - name: Terraform - Init
        id: init
        run: terraform init

      - name: Terraform - Validate
        id: validate
        run: |
          terraform validate
          echo "::set-output name=stdout::$(terraform validate -no-color)"

      - name: Terraform - Plan
        id: plan
        run: |
          terraform plan -out=plan.tmp
          terraform show -no-color plan.tmp >plan.out

      - name: Terraform - Show Plan in PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run_url = process.env.GITHUB_SERVER_URL + '/' + process.env.GITHUB_REPOSITORY + '/actions/runs/' + process.env.GITHUB_RUN_ID
            const run_link = '<a href="' + run_url + '">Actions</a>.'
            const fs = require('fs')
            const plan_file = fs.readFileSync('plan.out','utf8')
            const plan = plan_file.length > 65000 ? plan_file.toString().substring(0, 65000) + " ..." : plan_file
            const truncated_message = plan_file.length > 65000 ? "Output is too long and was truncated. You can read full Plan in " + run_link + "<br /><br />" : ""
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${plan}
            \`\`\`
            
            </details>
            ${truncated_message}

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ github.workspace }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
```
</details>

It will truncate too long output and create a link to the Actions to see full Plan
<img width="919" alt="Screenshot 2022-06-19 at 13 19 23" src="https://user-images.githubusercontent.com/88528265/174476355-115ec44f-4ca1-4830-9987-81179d873030.png">


And some notes about initial issue
1. Error `Argument list too long` is related to the variable assignment
   ```yaml
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
   ```
   And same error we got if we try to assign stdout to the javascript variable
   ```js
   const plan_env = `${{ steps.plan.outputs.stdout }}`
   ```
    In such a case a remained solution is to use a file

2. In case when we use file and it is too long, we get the following error
   ```
   RequestError [HttpError]: Validation Failed: {"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body is too long (maximum is 65536 characters)"}
   ```

3. By default, in [Terraform actions](https://github.com/hashicorp/setup-terraform) `terraform_wrapper: true` and in case of the short plan you will see some additional output - [How can I remove all the extraneous output from redirected output in GitHub Actions?](https://stackoverflow.com/questions/66496105/how-can-i-remove-all-the-extraneous-output-from-redirected-output-in-github-acti). But when it is disabled you can't directly access `Validation Output` and it will be empty. If we want to see it, we should set it manually.
