### ISSUE TITLE
Access matrix value inside script

### ISSUE THREAD

**Issue by aecorredor** [actions/github-script#271]
**Is your feature request related to a problem? Please describe.**

I'm running a job using a matrix, and I don't seem to have access to the `matrix` value inside the `context. From looking at the docs, it seems like it doesn't get included.

**Describe the solution you'd like**
Having access to the matrix inside the script through `context.matrix`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by joshmgross** [comment]
The `context` is available from `@actions/github` and doesn't contain the full context of a workflow - https://github.com/actions/toolkit/blob/main/packages/github/README.md

If there's something you want to reference from your workflow, you can pass it as an ENV variable to you step.

```yaml

      - uses: actions/github-script@v6
        env:
          MATRIX_VALUE: '${{ matrix.os }}'
        with:
          script: |
            console.log(process.env.MATRIX_VALUE)
```


You could reference it directly in the script too, but you'll need to be careful about values being escape as the entire `script` block is interpreted as JavaScript.

```js
console.log('${{ matrix.os }}')
```
