### ISSUE TITLE
`Cannot read properties of undefined` when `on:workflow_call`

### ISSUE THREAD

**Issue by Marvin-Brouwer** [actions/github-script#286]
**Describe the bug**
I have a step in my workflow to cancel other parallel steps if something fails.
This is important because my profiling steps can take a while.

```yml
    ###
    # 🗃 Cancel after test failure
    # Because the benchmark run runs in parallel with testing we need to cancel that when tests fail.
    ###
    - name: 🗃 Cancel after test failure
      if: ${{ failure() }}
      uses: actions/github-script@v6
      with:
          script: |
              github.actions.cancelWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: context.runId
              })
```

This has been working for a while now.
However, I recently split my workflow into multiple `on:workflow_call`s pointing to `yml` files.
Since then I get the following error:
```txt
TypeError: Cannot read properties of undefined (reading 'cancelWorkflowRun')
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4889:16), <anonymous>:3:16)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4890:12)
    at main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4944:26)
    at Module.272 (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4928:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:52:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1[15](https://github.com/Marvin-Brouwer/FluentSerializer/runs/7981979963?check_suite_focus=true#step:13:16)3:10)
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'cancelWorkflowRun')
```

**To Reproduce**
Copy the `yml` snipped into a composed pipeline as described.

**Expected behavior**
I'd expect a cancel to occur if a step fails.

**Screenshots**
`-`

**Desktop (please complete the following information):**
Pipeline: `ubuntu-latest`

**Smartphone (please complete the following information):**
`-`

**Additional context**
I suppose it's missing some context object or a secret here.
I just don't know which one.
