### ISSUE TITLE
execa not working with github script

### ISSUE THREAD

**Issue by CarlFMateus** [actions/github-script#346]
**Describe the bug**
I have tried to use execa with github script following the documentation that [github-script](https://github.com/actions/github-script#use-npm-packages) shows me, but deploying it doesn't work either using yarn or using npm.

This is the code that I am implementing in github actions

**To Reproduce**
```
jobs:
  tests:
    if: startsWith(github.head_ref, 'feature')
    runs-on: ubuntu-latest

    permissions: write-all

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm ci
      - run: npm install execa
      - name: Do you have a unit test?
        uses: actions/github-script@v6
        with:
          script: |
            const execa = require('execa')
            console.log(execa)
```

**Expected behavior**

**Screenshots**
<img width="1244" alt="Captura de Pantalla 2023-03-09 a la(s) 9 28 33 a m" src="https://user-images.githubusercontent.com/46789400/224056598-d489172e-97a3-438b-8bee-526d39e557a3.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
