### ISSUE TITLE
Incorrect Documentation for using npm packages

### ISSUE THREAD

**Issue by 0xDivyanshu** [actions/github-script#366]
**Describe the bug**

The documentation mentioned for using npm packages to is incorrect and not working. The mentioned README suggests using 
```
on: push

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install execa
      - uses: actions/github-script@v6
        with:
          script: |
            const execa = require('execa')

            const { stdout } = await execa('echo', ['hello', 'world'])

            console.log(stdout)
```

On actually running the above in my private github account I am getting error saying : 
```
[echo-input](https://github.com/0xDivyanshu/CI-CD-Github-Actions/actions/runs/4645398939/jobs/8221206860#step:5:21)
Unhandled error: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/CI-CD-Github-Actions/CI-CD-Github-Actions/node_modules/execa/index.js from /home/runner/work/_actions/actions/github-script/v6/dist/index.js not supported.
Instead change the require of /home/runner/work/CI-CD-Github-Actions/CI-CD-Github-Actions/node_modules/execa/index.js in /home/runner/work/_actions/actions/github-script/v6/dist/index.js to a dynamic import() which is available in all CommonJS modules.
```

**To Reproduce**

1. Simply create a actions workflow and use the above mentioned yaml as actions file and initiate the workflow.
