### ISSUE TITLE
Is there any possibility to use file as a script?

### ISSUE THREAD

**Issue by extempl** [actions/github-script#38]
Maybe using `cat file` or something? 
If no, is it possible to add? 

Because it is not that easy to write normal js code inside yaml.

**Comment by extempl** [comment]
End up with following solution:

```
      - run: echo "::set-output name=js::$(tr '\n' ' ' < ./.github/diffWithMaster.js)"
        id: diffJS
        name: service run

      - name: Getting diff with master
        id: diff
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: ${{ steps.diffJS.outputs.js }}
```

`tr '\n' ' '` for merging file into one line, so make sure you have `;` in the js everywhere. 
Also, so far this is the only solution to nicely merge output (`echo` won't work on github actions for some reason).

Also note that in this case you won't be able to use any global non-js variables inside the js script, like `head: '${{github.event.ref}}'`, so you will be able to use only those variables that github-script provides.

**Comment by DannyvanderJagt** [comment]
Using files instead of strings would be nice. Will save a lot of code in my .yml files and allows me to re-use scripts I already use for other stuff.

I made a local PR to add file support. I'm testing it now and will create a PR here tomorrow.

**Comment by lukka** [comment]
Having arbitrary code to run inside to the yaml file, it is not a good idea, for many reasons:
 - not testable with unit test;
 - not manually testable;
 - maintenance headache;

IMO yaml is good to contain declarative statements only and it should be as concise as possible.

Having file as an input should be coming from the design review, not from customer feedback.

**Comment by extempl** [comment]
> Having file as an input should be coming from the design review, not from customer feedback.

In fairness, it is true when you selling your product, and there are customers. Otherwise, when you building some tool for yourself and publishing to help others - it is not really fair to say like that :)

**Comment by lukka** [comment]
My fault, I completely missed this action is _experimental_ indeed as stated in the README.md file. I take it back :)

**Comment by jclem** [comment]
@lukka We're not going to remove the ability to inline the script—we've seen that there's a huge demand for it in development lifecycle flows where a user just wants to write one file that accomplishes the task of something like commenting on an issue.

That said, I also think there's value in being able to run a file, and I plan on adding this soon.

**Comment by jclem** [comment]
The more I think about it, the less I'm convinced that adding this will really add that much value. If you want to run a file instead of a plain script, it's quite easy to do:

```yaml
uses: actions/github-script@v0.9.0
  with:
    script: |
      const path = require('path')
      return require(path.resolve('my-script.js'))({context})
```

And then, in your file:

```javascript
module.exports = ({context}) => {
  return context.payload.client_payload.value
}
```

It's also safe to use a module exporting an async function in this way as long as you `await` it in the inline script.
