### ISSUE TITLE
Add support for the "merge_group" event

### ISSUE THREAD

**Issue by elioduarte** [actions/github-script#388]
**Is your feature request related to a problem? Please describe.**
Can't use the actions/github-script with [merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue):

Error: This action only supports pull requests and pushes, merge_group events are not supported. Please submit an issue on this action's GitHub repo if you believe this in correct.

**Describe the solution you'd like**
Being able to use the actions/github-script with the [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)

**Comment by eduardomoroni** [comment]
@joshmgross @rentziass do you think this is something we could raise a PR for?

**Comment by joshmgross** [comment]
Could you clarify where you're seeing this message?
Do you have an example workflow or run?

This action isn't restricted to specific events.

**Comment by eduardomoroni** [comment]
![image](https://github.com/actions/github-script/assets/823150/9507f289-3651-46c0-a5fb-03c0cb224669)

>Do you have an example workflow or run?
Our repo is private but thee workflow looks like this

```
name: 'PR — Release'

permissions:
# redacted

concurrency:
  group: pr_release_${{ github.head_ref }}
  cancel-in-progress: true

on:
  merge_group:
  pull_request:
    branches:
      - master

# a lot of other things

  prettier:
    name: 'Prettier Format Check'
    runs-on: web-monorepo-exclusive.default
    timeout-minutes: 10
    steps:
      - name: Get changed files
        id: get-changed-files
        uses: actions/github-script@v6
        with:
          script: |
            const getChangedFiles = require('./.github/workflows/scripts/get_changed_files.js')
            await getChangedFiles({ github, context, core })
```
