### ISSUE TITLE
Add support for graphql

### ISSUE THREAD

**Issue by JohannesRudolph** [actions/github-script#39]
In addition to rest.js it would also be great to have a pre-configured graphql API available:

https://github.com/octokit/graphql.js

**Comment by jclem** [comment]
I'll validate this works before closing this, but since the `github` object is from the [Actions Toolkit GitHub package](https://github.com/actions/toolkit/tree/master/packages/github), this should be available at `github.graphql`. I'll verify before closing this.

**Comment by jclem** [comment]
Okay! Confirmed that this works.

```yaml
on: repository_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: get-login
        uses: actions/github-script@0.9.0
        with:
          script: |
            return github.graphql(`
              query {
                viewer {
                  login
                }
              }
            `)
      - run: echo '${{steps.get-login.outputs.result}}'
```
