### ISSUE TITLE
Unable to use file as script

### ISSUE THREAD

**Issue by LeonardoBerlatto** [actions/github-script#390]
**Describe the bug**
I am exporting a function with the code I want to execute but I keep getting this error:
<img width="1093" alt="Screenshot 2023-05-29 at 17 30 16" src="https://github.com/actions/github-script/assets/36887738/4340fc7b-b9ee-4b5a-9de1-71b42d31e703">

**To Reproduce**
1. Create a script as a file on .github/scripts
2. Try to import it and use it with the action

**Expected behavior**
Code execute normally as if hardcoded on the workflow file

**Screenshots**
<img width="756" alt="image" src="https://github.com/actions/github-script/assets/36887738/11b4b533-0435-4b76-a322-7ff084018db0">

<img width="330" alt="image" src="https://github.com/actions/github-script/assets/36887738/29761f48-055c-4910-98a3-81b7edd6fe8e">

<img width="783" alt="image" src="https://github.com/actions/github-script/assets/36887738/a68eba20-5c04-44f8-908b-26b882ededc3">

**Comment by joshft91** [comment]
In your yaml file, instead of `'.github/scripts/remove-pr-artifacts.js'` try `'./.github/scripts/remove-pr-artifacts.js'` (leading `./`).

We use a file as a script in some places and I needed the leading `./` to get ours to work.

**Comment by LeonardoBerlatto** [comment]
> In your yaml file, instead of `'.github/scripts/remove-pr-artifacts.js'` try `'./.github/scripts/remove-pr-artifacts.js'` (leading `./`).
> 
> We use a file as a script in some places and I needed the leading `./` to get ours to work.

@joshft91 
I haven't tried that, instead I used:

<img width="806" alt="Screenshot 2023-06-23 at 16 39 57" src="https://github.com/actions/github-script/assets/36887738/d3e19e51-6c8f-4b82-bc89-a5c85f29f045">

But, anyway, if you have to use relative path, it should be in the docs at least

**Comment by joshmgross** [comment]
You can either use a relative path or the absolute path via `github.workspace`.

Our documentation has examples of both.

Relative - https://github.com/actions/github-script#run-a-separate-file-with-an-async-function

```yaml
      - uses: actions/github-script@v6
        env:
          SHA: '${{env.parentSHA}}'
        with:
          script: |
            const script = require('./path/to/script.js')
            await script({github, context, core})
```

Absolute - https://github.com/actions/github-script#use-esm-import

```yaml
      - uses: actions/github-script@v6
        with:
          script: |
            const { default: printStuff } = await import('${{ github.workspace }}/src/print-stuff.js')

            await printStuff()
```
