### ISSUE TITLE
Trailing slash on api calls causes 404 error

### ISSUE THREAD

**Issue by w0244079** [actions/github-script#394]
When I try to make a call such as 

github.rest.issues.get({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
})

The underlying api call is currently logged as 

request: {
    method: 'GET',
    **url: 'https://api.github.com/repos/[org]/[repo]/issues/',**
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/github-script octokit-core.js/3.6.0 Node.js/16.16.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }

the logged url has a trailing slash at the end which seems to be causing a 404 response from the api. When I do a get request to the url and remove the trailing slash, the api returns data.

Looks like the trailing slash at the end of the url is causing a problem...

example:
https://api.github.com/repos/facebook/react-native/issues - returns data
https://api.github.com/repos/facebook/react-native/issues/ - returns 404

Is the url with the trailing slash generated in github-scripts or perhaps one of the supporting packages?

**Comment by victor-mariano-leite** [comment]
Same here

**Comment by joshmgross** [comment]
> Is the url with the trailing slash generated in github-scripts or perhaps one of the supporting packages?

From your code:
```js
github.rest.issues.get({
  issue_number: context.issue.number,
  owner: context.repo.owner,
  repo: context.repo.repo,
})
```

Is it possible that `context.issue.number` is undefined?
Could you share the rest of the workflow or at least how you're triggering it?

**Comment by tpaksu** [comment]
Same here with a different endpoint

```
const pulls = await octokit.pulls.get( {
    owner: GITHUB_REPO_OWNER,
    repo: GITHUB_REPO,
    head: `${ GITHUB_REPO_OWNER }:${ currentBranch }`
} );
```

Produces:

```
https://api.github.com/repos/x/y/pulls/?head=z:w
```

Which results with a 404 response, but 
```
https://api.github.com/repos/x/y/pulls?head=z:w
```
returns the correct data.

**Comment by bhargavpanth** [comment]
Hi @joshmgross ! It does seem like the `context.issue.number` is indeed an `undefined`, in my case. Looking at the context object, it doesn’t look like there is a `issue` property in there. Is there a pre-requisite to fetch the issue number?

The way I am triggering my workflow is like

```yaml

name: something

on:
  push:
    branches: [ "master", "main" ]

permissions:
    contents: write
    pull-requests: write

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
        - name: Check out
          uses: actions/checkout@v3
          with:
            submodules: recursive
            token: ${{ secrets.PAT_GITHUB_ACTIONS }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.1.7

        - name: Terraform fmt
          id: fmt
          working-directory: ./terraform
          run: terraform fmt -check
          continue-on-error: true

        - name: Terraform init
          id: init
          working-directory: ./terraform
          run: |
            terraform init \
            -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

        - name: Terraform select workspace
          id: workspace
          working-directory: ./terraform
          run: terraform workspace select production

        - name: Terraform validate
          id: validate
          working-directory: ./terraform
          run: terraform validate -no-color

        - name: Terraform plan
          id: plan
          working-directory: ./terraform
          run: |
            TF_VAR_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            TF_VAR_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            terraform plan -no-color \
            -var-file production.tfvars

        - uses: actions/github-script@v6
          env:
            PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
                #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
                #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
                <details><summary>Validation Output</summary>
        
                \`\`\`\n
                ${{ steps.validate.outputs.stdout }}
                \`\`\`
        
                </details>
        
                #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
        
                <details><summary>Show Plan</summary>
        
                \`\`\`\n
                ${process.env.PLAN}
                \`\`\`
        
                </details>
        
                *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \terraform, Workflow: \`${{ github.workflow }}\`*`;

                console.log(`Context: ${JSON.stringify(context)}`);
        
                github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: output
                })
  
        - name: Terraform Plan Status
          if: steps.plan.outcome == 'failure'
          run: exit 1
  
        - name: Terraform Apply
          working-directory: ./terraform
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: |
            TF_VAR_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            TF_VAR_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            terraform apply \
                -auto-approve \
                -input=false \
                -var-file production.tfvars

```

For context, I am using this Hashicorp's Github Actions [example](https://github.com/hashicorp/setup-terraform)
