### ISSUE TITLE
How to run in a specific directory

### ISSUE THREAD

**Issue by kaykhan** [actions/github-script#412]
I have a workflow which makes use of the `working-directory`. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun although this does not work with `uses`. 

```
defaults:
 run:
  working-directory: applications/prod/kafka-ui
...
```

Below i use github-script.

```
    - name: Terraform Comment
      uses: actions/github-script@v6
      env:
        TFPLAN_IDENTIFIER: "${{ steps.plan.outputs.tfplan_identifier}}"
        PLAN_OUTPUT: "${{ steps.plan.outputs.stdout }}"
        PLAN_ERROR: "${{ steps.plan.outputs.stderr }}"
      with:
        script: |
 ```
 
 How do i force github-script to run in a specific directory.
