### ISSUE TITLE
Can't store NODE_OPTIONS output parameter using '$GITHUB_ENV' command

### ISSUE THREAD

**Issue by Bekhzod96** [actions/github-script#418]
**Describe the bug**
Start getting error 
```
Error: Can't store NODE_OPTIONS output parameter using '$GITHUB_ENV' command
```

before it was working fine Here is causing code section
```
core.exportVariable(NODE_OPTIONS, "--max-old-space-size=5120");
```

**To Reproduce**
```yml
  - name: Setup Environment Variables
    uses: actions/github-script@v6
     with:
       script: |
         core.exportVariable(NODE_OPTIONS, "--max-old-space-size=5120");
```

**Expected behavior**
It should set in environmental variable `NODE_OPTIONS`

**Screenshots**
<img width="743" alt="Screenshot 2023-09-12 at 18 41 32" src="https://github.com/actions/github-script/assets/35173991/f0656cd9-fb51-445d-bac9-fbe1573b546b">

**Additional context**
Here is main use-case to set environmental variables from variables 
```yml
 - name: Setup Environment Variables
   uses: actions/github-script@v6
     env:
       VARS: ${{ toJSON(vars) }}
     with:
       script: |
         const vars = JSON.parse(process.env.VARS)
         for (const key in vars) {
             core.exportVariable(key, vars[key]);
         }
```

**Comment by arunstar** [comment]
Cause : https://github.com/actions/runner/pull/2775

**Comment by rafaelsouzaf** [comment]
`+1`

Github action yaml file:

```
build-node:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-versions: ['16', '17']
    name: Node ${{ matrix.node-versions }} Testing

steps:
   ...
   ...
    - name: Override NODE options for the most recent version
      if: matrix.node-versions == '17'
      run: export NODE_OPTIONS=--openssl-legacy-provider

```

Error:

```
echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
  shell: /usr/bin/bash -e {0}
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX

Error: Can't store NODE_OPTIONS output parameter using '$GITHUB_ENV' command.
```
