### ISSUE TITLE
Unrecognized named-value: 'context'

### ISSUE THREAD

**Issue by arg** [actions/github-script#43]
This is the workflow I created (basically copied it from the readme):

```yml

name: coverage

on:
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  coverage_link:
    runs-on: ubuntu-latest
    steps:
      - name: Link the coverage report
        uses: actions/github-script@0.9.0
        with:
          github-token: "${{secrets.GITHUB_TOKEN}}"
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "See the coverage report at https://${{secrets.reports_host}}/${{secrets.reports_path}}/${{context.issue.number}}"
            })
```

The workflow is supposed to put a comment at any new pull request, however the execution fails with:
```
The workflow is not valid. .github/workflows/coverage.yml (Line: 16, Col: 19): Unrecognized named-value: 'context'. Located at position 1 within expression: context.issue.number
```
