### ISSUE TITLE
unable to create commit

### ISSUE THREAD

**Issue by penglei0** [actions/github-script#431]
**Describe the bug**
Fail to call `createCommit`

**To Reproduce**

Please use the following yaml to reproduce。
```yaml
jobs:
  use-github-script:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 2
        - name: Create a new file
          run: |
            touch ${{github.workspace}}/log.txt
            echo "parent=`git rev-parse HEAD`" >> "$GITHUB_ENV"
            git hash-object -w ${{github.workspace}}/log.txt
            git update-index --add ${{github.workspace}}/log.txt
            echo "object_tree=`git write-tree`" >> "$GITHUB_ENV"
        - name: Commit to repo
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                const commit_msg = "feat: example of add a file"
                const parent = "${{ env.parent}}";
                const object_tree = "${{ env.object_tree}}"";
                const response = await github.rest.git.createCommit({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    message: commit_msg,
                    tree: object_tree,
                    parents: [parent]
                });
            
```

**Expected behavior**
expect to run the createCommit successfully

**Screenshots**
<img width="818" alt="image" src="https://github.com/actions/github-script/assets/101799503/304b5241-af02-4395-85d5-bd603866b70f">
