### ISSUE TITLE
workflow_sha and workflow_ref are not populated

### ISSUE THREAD

**Issue by Jiri-Stary** [actions/github-script#446]
**Describe the bug**

Reference to github workflow_ref and workflow_sha is not populated

See the code below - 

echoing the variable works, but the same code is not available in github-script:

```

name: test-workflow-version

on:
  push:
    branches:
      - main

jobs:
  log-version:
    runs-on:  gh-larger-linux-small

    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Get and Log Pipeline Version
      uses: actions/github-script@v7
      with:
        script: |
          
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          // Get the ref (branch or tag) of the workflow file
          const workflowCommitSha = github.workflow_sha;
          const workflowRef = github.workflow_ref;

          console.log(`Workflow Commit ref : ${workflowRef }`);
          console.log(`Workflow Commit SHA: ${workflowCommitSha}`);

  log-version2:
    runs-on: gh-larger-linux-small
    steps:
     - name: checkout
       uses: actions/checkout@v4

     - run: |
          echo "GitHub Context Repository: ${{ github.repository }}"
          echo "workflow ref ${{ github.workflow_ref }}"
          echo "workflow sha ${{ github.workflow_sha }}"

```

**Comment by mountainash** [comment]
Could you try passing it in through ENV to the script like:

```yml
      - name: Get and Log Pipeline Version
        uses: actions/github-script@v7
        env:
          WORKFLOW_SHA: ${{ github.workflow_sha }}
          WORKFLOW_REF: ${{ github.workflow_ref }}
        with:
          script: |
            const { WORKFLOW_SHA,  WORKFLOW_REF } = process.env
            console.log(`Workflow Commit ref: ${WORKFLOW_REF }`)
            console.log(`Workflow Commit SHA: ${WORKFLOW_SHA}`)
```
