### ISSUE TITLE
Octokit's `octokit.rest.copilot.getCopilotSeatDetailsForUser` is renamed/unavailable

### ISSUE THREAD

**Issue by Battleman** [actions/github-script#470]
**Describe the bug**
The properties defined in `octokit.rest.copilot` are not consistent with the documentation. It seems the function `getCopilotSeatDetailsForUser` has been renamed to `getCopilotSeatAssignmentDetailsForUser`.
According to the [octokit doc](https://octokit.github.io/rest.js/v20#copilot), the function to get a user's copilot details is done with 
```
octokit.rest.copilot.getCopilotSeatDetailsForUser({
  org,
  username,
});
```
Using this method within this action fails.

**To Reproduce**
1. In a repository, create basic action 
```yaml
name: Issue Workflow
on:
  issues:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run GitHub Script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(Object.keys(github.rest.copilot))
            console.log(github.rest.copilot.getCopilotSeatDetailsForUser({
              org: "MyOrg",
              username: "MyUsername",
            }));
```
2. Trigger the action with an issue
3. The output is 
```text
 [
  'addCopilotForBusinessSeatsForTeams',
  'addCopilotForBusinessSeatsForUsers',
  'cancelCopilotSeatAssignmentForTeams',
  'cancelCopilotSeatAssignmentForUsers',
  'getCopilotOrganizationDetails',
  'getCopilotSeatAssignmentDetailsForUser',
  'listCopilotSeats'
]
TypeError: github.rest.copilot.getCopilotSeatDetailsForUser is not a function
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35424:16), <anonymous>:4:33)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35425:12)
    at main (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35522:26)
    at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:35497:1
    at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:35553:3
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35556:12)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
```

**Expected behavior**
The documented function `getCopilotSeatDetailsForUser` should work, as it does locally.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 125

**Additional context**
(I'm not sure if the problem comes from here specifically, but because the same code works locally but not within this action, it's my first hunch)
