### ISSUE TITLE
Exec is not defined in the script as opposed to what documentation states

### ISSUE THREAD

**Issue by lonelyelk** [actions/github-script#503]
**Describe the bug**

Running a simple action with `exec` call fails with `TypeError: exec is not a function`. Trying to explicitly require it fails with `Cannot find module '@actions/exec'`

**To Reproduce**
1. Create an action:

```yaml
      - name: Check if exec actually works
        uses: actions/github-script@v7
        with:
          script: |
            const result = await exec('echo', ['hello'])
```

2. See it fail

**Expected behavior**

Expected `exec` to be defined as documentation states

**Additional context**

```
TypeError: exec is not a function
    at eval (eval at callAsyncFunction (/runner/_work/_actions/actions/github-script/v7/dist/index.js:35424:16), <anonymous>:32:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/runner/_work/_actions/actions/github-script/v7/dist/index.js:35[52](https://github.com/cresta/config/actions/runs/12377417457/job/34546874362?pr=126666#step:6:53)2:20)
Error: Unhandled error: TypeError: exec is not a function
```

**Comment by lonelyelk** [comment]
Maybe it is connected to the fact that this is a JS project with a  `package.json` in the root. Installing `@actions/exec` globally beforehand didn't help either. Calling `require` still results in the module not found.

**Comment by joshmgross** [comment]
👋 Hey @lonelyelk,

> `exec` A reference to the [@actions/exec](https://github.com/actions/toolkit/tree/main/packages/exec) package


That means `exec` itself is not the exec function you expect, hence the error "exec is not a function" that you received.

You want `exec.exec`

https://github.com/actions/toolkit/tree/main/packages/exec#basic


```yaml
      - name: Check if exec actually works
        uses: actions/github-script@v7
        with:
          script: |
            const result = await exec.exec('echo', ['hello'])
```
