### ISSUE TITLE
How to pass parameters to the script?

### ISSUE THREAD

**Issue by acidos** [actions/github-script#56]
I am trying to pass variable from previous action to `github-script`, but can't figure out syntax. Is it possible at all?

**Comment by jclem** [comment]
The easiest way to do this is via Actions' expression evaluation syntax (`${{ }}`). Assuming you want to use the output from a previous step in your github-script action, you could do something like this:

```yaml
- uses: actions/github-script@v1
  with:
    script: |
      console.log(${{ steps.step-id.outputs.output-name }})
```


This assumes that you have a previous step whose ID is "step-id" and that whose outputs include a value called "output-name". See ["About contexts and expressions"](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions) and ["steps context"](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context).

**Comment by mdvorak** [comment]
This is a great way to introduce code-injection. I discourage this.

Scenario:
Previous step reads commit message, issue title, or any other user-provided string and stores it as output.
In this step, you use Actions expression.

So, given previous example, I'll create e.g. commit message with:
```
harmless commit'); github.repos.addCollaborator({...context.repo, 'mdvorak'}); console.log('you have been hacked
```

this would indeed expand into
```
- uses: actions/github-script@v1
  with:
    script: |
      console.log('harmless commit'); github.repos.addCollaborator({...context.repo, 'mdvorak'}); console.log('you have been hacked')
```

**Comment by y-nk** [comment]
If you plan to use `core.getInput` in a composite action, the values won't be provided because of https://github.com/actions/runner/issues/665 **but you can fix it easily**

just provide the inputs manually as env vars as suggested above by @jclem with the expected format by `core.getInput`:

```yaml
inputs:
  foo:
    required: true
# ...
- uses: actions/github-script@v7
  env:
    INPUT_FOO: ${{ inputs.foo }} # this part hotfixes the bug
  with:
    script: |
      console.log(core.getInput('foo'))
```

note: the code of `getInput` requires the env var to be named `INPUT_{UPPERCASED_PARAM_PASSED_TO_GETINPUT`
