### ISSUE TITLE
Expose `strategy` and `matrix` variables in `context`

### ISSUE THREAD

**Issue by tony-pizza** [actions/github-script#615]
**Is your feature request related to a problem? Please describe.**

I'm using a matrix and I want to access matrix- and strategy-related variables in my github-script. The only way to do that is to do the env var dance:

```yml
# ...
strategy:
  matrix:
    group: [1, 2]
steps:
  - uses: actions/github-script@v7
    env:
      MATRIX_GROUP: ${{ matrix.group }}
      MATRIX_NUM_GROUPS: ${{ strategy.job-total }}
    with:
      script: |
        const group = parseInt(process.env.MATRIX_GROUP)
        const numGroups = parseInt(process.env.MATRIX_NUM_GROUPS)
```

**Describe the solution you'd like**
It would be great if these could live in `context` to avoid mucking with env vars. That seems like an intuitive home for them. Something like...

```yml
# ...
strategy:
  matrix:
    group: [1, 2]
steps:
  - uses: actions/github-script@v7
    with:
      script: |
        const group = parseInt(context.strategy.matrix.group)
        const numGroups = context.strategy.totalJobs
```
