### ISSUE TITLE
Misleading "Cannot find module" error message

### ISSUE THREAD

**Issue by j-ulrich** [actions/github-script#68]
When using the approach described in the ["Run a separate file"](https://github.com/actions/github-script#run-a-separate-file), I encountered a very misleading error message:
```
Error: Cannot find module '/home/runner/work/project-name/project-name/path/to/separate-script.js'
    at webpackEmptyContext (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:9475:9)
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:7985:56), <anonymous>:4:7)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:7986:12)
    at main (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:8011:26)
    at Module.833 (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:7995:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:37:19)
    at /home/runner/work/_actions/actions/github-script/v2/dist/index.js:43:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v2/dist/index.js:46:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30) {
  code: 'MODULE_NOT_FOUND'
}
```
when using a workflow like this:
```yaml
on: push

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          script: |
            const path = require('path')
            const scriptPath = path.resolve('./path/to/separate-script.js')
            await require(scriptPath)({context})
```

It kept me busy for a few hours because I tried to find out why `separate-script.js` could not be found like the error message says.
**But in fact, it was a module that was required by `separate-script.js` which could not be found.**

So `separate-script.js` did a `require( 'some-missing-module' )` and the `some-missing-module` could not be found but the error message led into a completely wrong direction.

Here is an example showing the behavior: https://github.com/j-ulrich/github-actions-test/runs/879829284?check_suite_focus=true#step:3:11

To save other people from running into this, it would be great if this could be fixed if at all possible.
