### ISSUE TITLE
import npm packages

### ISSUE THREAD

**Issue by mrchief** [actions/github-script#73]
Is it possible to require npm packages in the script or script file? Something like 

```
script: |
  const pkg = require('some-npm-package')
  pkg.useMethod()
```

**Comment by jclem** [comment]
Good question—this action won't do this automatically for you, but you can explicitly require modules you've installed in prior steps (note the awkward need to reference `GITHUB_WORKSPACE`—I haven't found a workaround for this, yet):

```yaml
name: Test "require" of an npm module

# Assuming that this repository has a "package.json" with "cowsay" in it:

on: workflow_dispatch

jobs:
  cowsay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - uses: actions/github-script@v2
        with:
          script: |
            const {say} = require(`${process.env.GITHUB_WORKSPACE}/node_modules/cowsay`)
            console.log(say('hello'))
```
