### ISSUE TITLE
What version of node is used in Actions to run gh-scripts?

### ISSUE THREAD

**Issue by ahmadnassri** [actions/github-script#76]
The documentation does not detail what version of node is used to execute, and whether `actions/setup-node` would of any use / relevance?

**Comment by jclem** [comment]
Hi @ahmadnassri, good question! Unless `actions/setup-node` is explicitly used, the version of Node will be whatever is installed in the virtual environment you're using (for example `ubuntu-latest`). This is documented in ["Software installed on GitHub-hosted runners"](https://docs.github.com/en/actions/reference/software-installed-on-github-hosted-runners). For example, the current `ubuntu-latest`, which is 20.04 LTS, [uses Node.js 12.18.3](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#ubuntu-2004-lts).

**Comment by ahmadnassri** [comment]
interesting... setup-node with 14 didn't seem to have the desired effect in my testing. (was using Null Coalescing Operator in my script) but ... I've moved to a separate full action now so I can't revisit easily ...

regardless, this would be useful to document in the readme.

thanks

**Comment by jclem** [comment]
@ahmadnassri Can you point me to the workflow file, if it's public?

**Comment by ahmadnassri** [comment]
it isn't public unfortunately

**Comment by ahmadnassri** [comment]
I'll keep this issue in my tabs and might come back to it later and make another test on a public repo to share

**Comment by ylemkimon** [comment]
AFAIK, the runner runs JS action with Node.js 12 regardless of `actions/setup-node`:
https://github.com/actions/github-script/blob/fc4d6279013dd0c4f4db0c7c21ff1a1c46e5c8ea/action.yml#L30

**Comment by kf6kjg** [comment]
The current `ubuntu-latest` runner is `Ubuntu 20.04.2` which, [according to the docs](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) is provided with `Node 14.16.1`.

I set up a job with the following statements:
```yaml
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - run: |
          console.debug({nodeVersion: process.version});
        shell: node --input-type=module {0}

      - uses: actions/github-script@v4.0.2
        with:
          script: |
            console.debug({nodeVersion: process.version});
```

And got the following as results from the console logs:
```
{ nodeVersion: 'v14.16.1' }

{ nodeVersion: 'v12.13.1' }
```

So I'd say that this action is overriding the version supplied by both the environment AND `actions/setup-node`.  This is very annoying as it means that code I compiled from TS to JS for ES2020 will not execute due to the usage of the nullish coalescing operator and other features introduced in 14.

Please revisit this.
