### ISSUE TITLE
Unrecognized named-value: 'github' in defaults.run

### ISSUE THREAD

**Issue by phamnhuvu-dev** [actions/github-script#81]
I am using github runner to build app for Android, iOS and Web. We have multiple sharing code projects at the application layer, so we need to config working-directory.

If I using this hard code. The runner works well
```yml
defaults:
  run:
    working-directory: manabie_teacher
```
Then I update script to require input for flexible building, but It's not working.
```yml
name: Delivery
on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Flavor'
        required: true
        default: 'staging'
      working-directory:
        description: 'Working Directory'
        required: true
        default: 'manabie_teacher'

defaults:
  run:
    working-directory: ${{ github.event.inputs.working-directory }}

jobs:
  delivery-android:
    runs-on: [self-hosted, macOS]
    steps:
      - run: echo "::set-env name=DART_HOME::$RUNNER_TOOL_CACHE/flutter/bin/cache/dart-sdk/bin"
      - run: echo "::set-env name=FLUTTER_HOME::$RUNNER_TOOL_CACHE/flutter/bin"
      - run: echo "::set-env name=ANDROID_HOME::$RUNNER_TOOL_CACHE/sdk"
      - run: echo "::add-path::$DART_HOME"
      - run: echo "::add-path::$FLUTTER_HOME"
      - run: echo "::add-path::$ANDROID_HOME"
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - run: flutter pub get

      - name: Build Staging
        if : ${{ github.event.inputs.flavor == 'staging' }}
        run: make build-staging-android
      - name: Push Staging
        if : ${{ github.event.inputs.flavor == 'staging' }}
        run: make push-android token=${{ secrets.FIREBASE_TOKEN }}

      - name: Build Production
        if: ${{ github.event.inputs.flavor == 'production' }}
        run: make build-production-android
      - name: Push Production
        if: ${{ github.event.inputs.flavor == 'production' }}
        run: make push-prod-android token=${{ secrets.FIREBASE_TOKEN }}
```

Error:
```
The workflow is not valid. .github/workflows/delivery.yml (Line: 16, Col: 24): Unrecognized named-value: 'github'. Located at position 1 within expression: github.event.inputs.working-directory
```
