### ISSUE TITLE
Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files.

### ISSUE THREAD

**Issue by theowenyoung** [actions/github-script#97]
**Describe the bug**

When use `core.exportVariable('envVar', 'Val');` as script, there is an error:

```bash
Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
Log link: https://github.com/theowenyoung/test-actions/actions/runs/359544404

**To Reproduce**

```yaml
"on":
  - workflow_dispatch
jobs:
  print:
    name: Print 0
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: actions/github-script@v3
        with:
          script: |
            core.exportVariable('envVar', 'Val');
            return 1
```

From https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ 

I think the action should update the `@actions/core` dependence to `1.2.6`
